# Generated by Django 5.2.8 on 2025-11-16 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(choices=[('none', 'None'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default='none', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overdue_notified', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20, null=True)),
                ('recurrence_interval', models.IntegerField(default=1, help_text='Every N days/weeks/months')),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='Days of week for weekly recurrence [0=Monday, 6=Sunday]')),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('recurrence_count', models.IntegerField(blank=True, help_text='Number of occurrences', null=True)),
                ('recurrence_created_count', models.IntegerField(default=0, help_text='Number of tasks created so far')),
                ('next_recurrence_date', models.DateField(blank=True, null=True)),
                ('parent_task', models.ForeignKey(blank=True, help_text='Original recurring task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(choices=[('none', 'None'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default='none', max_length=12)),
                ('due_date_offset', models.IntegerField(default=0, help_text='Days offset from creation date (0 = same day, 1 = next day, etc.)')),
                ('order', models.IntegerField(default=0, help_text='Order of items in template')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.tasktemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
