# Generated by Django 5.2.8 on 2025-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('none', 'None'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default='none', max_length=12),
        ),
    ]
