# Generated by Django 5.2.8 on 2025-11-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
